name: upgrade_lifecycle
description: CVO, MCO, Installer variants, LCA, TALM
components:
- Cluster Version Operator
- Machine Config Operator
- Machine Config Operator / platform-vsphere
- Installer / openshift-installer
- Installer / Agent based installation
- Installer / Assisted installer
- Installer / Disconnected UI
- Installer / OpenShift on OpenStack
- Installer / vSphere
- Installer / PowerVC
- Installer / PowerVS
- Installer / Nutanix
- LCA operator
- TALM Operator
- oc-mirror
